title: 东木咨询博客
description: 东木咨询，你的人生发展伙伴

url: https://long-haul.netlify.app
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 20

navigation:
    - title: 首页
      url: /index.html
    - title: 人生发展问答
      url: /life-development
    - title: 美好生活
      url: /good-life
    - title: 咨询手记
      url: /counseling
    - title: 角色榜样
      url: /role-model
    - title: 东木和我
      url: /dongmu-and-me
    - title: 回到官网
      url: https://www.dongmu.cc

social:
    email: e@dongmu.cc
    weixin_qr: "https://mp.weixin.qq.com/s/6yRRBTVeaGsX5K3_m9CWpQ"
    zsxq_qr: "https://t.zsxq.com/14212OcTn"


google_analytics: 

disqus:
    shortname: brianmaierjr
