title: 东木咨询博客
description: 欢迎来到的东木咨询~

url: https://long-haul.netlify.app
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: 主页
      url: /index.html
    - title: 咨询手记
      url: /category/counseling
    - title: 美好情绪
      url: /category/emotion  
    - title: 角色榜样
      url: /category/role-model
    - title: 课程&咨询
      url: /category/course
    - title: 关于东木
      url: /about
    - title: 回到官网
      url: https://www.dongmu.cc

social:
    github: brianmaierjr
    twitter: brianmaierjr
    facebook: brianmaierjr
    email: brimaidesigns@gmail.com
    linkedin: brianmaierjr
    youtube: RickAstleyYT
    tumblr: i-am-a-fish

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
